### ISSUE TITLE
TTL is hardcoded to 60 seconds

### ISSUE THREAD

**Issue by m6w6** [ctrlaltcoop/certbot-dns-hetzner#1]
The TTL for created records is hardcoded to 60 seconds in dns_hetzner.py, shouldn't it use the `dns-hetzner-propagation-seconds` option?

**Comment by l0rn** [comment]
Actually no - the propagation seconds is not the TTL, it is the time that is waited until certbot will check whether the challenge has propagated throughout the DNS hierarchy. As different providers tend to propagate in a different amount of time it's configurable. 
The TTL should be set to a sane default which i chose to be 60 seconds. I can't see why this needs to be configurable.
