### ISSUE TITLE
Compatibility with Certbot >= 2.0.0

### ISSUE THREAD

**Issue by Bloodsoul** [ctrlaltcoop/certbot-dns-hetzner#19]
See https://github.com/certbot/certbot/releases/tag/v2.0.0 for the changes.
At least the line `The zope based interfaces in certbot.interfaces have been removed in favor of the abc based interfaces found in the same module.` will be relevant for certbot-dns-hetzner to run again.

**Comment by l0rn** [comment]
Yep, will update this project in the course of the coming days

**Comment by l0rn** [comment]
2.0 is out and should be certbot 2 compatible
