### ISSUE TITLE
Snap Repository containing old version - Plugin not found in any package manager either (except pip)

### ISSUE THREAD

**Issue by hjan** [ctrlaltcoop/certbot-dns-hetzner#22]
Hi there,

at the moment the [Snap repository](https://snapcraft.io/certbot-dns-hetzner) contains a rather old version (`1.22.0`) of the dns-hetzner plugin. And the version published there comes from an [inactive/archived fork](https://github.com/BigMichi1/certbot-dns-hetzner) from this repositoy. There are also no packages found for the dns-hetzner plugin in any package manager (e.g. Ubuntu apt), whilst quite a few prominet providers are available (Cloudflare, DigitalOcean, Google, Linode, etc.).

It would be really nice to have the Hetzner plugin somewhat officially available and documented everywhere.
For example, the providers mentioned above are also documented and listed in the official certbot doc here:
https://eff-certbot.readthedocs.io/en/stable/using.html#dns-plugins

If I'm understanding it correctly (at least it seems that way), this Hetzner plugin is a community driven project and not officially
developed and published by Hetzner (though, they provide some documentation for it: https://community.hetzner.com/tutorials/letsencrypt-dns - which probably comes from the same community ;) )

So, I wanted to asked rather naively whether there would be a chance to get this very useful plugin packaged for any package manager other than just pip because there might be good reasons not to use pip for some people (personally, an updated version in snap would be plenty already!).

Thanks a lot for any comments on this.

**Comment by fupduck** [comment]
Hey  @hjan 

We did not start the snap repository. 
We currently are not planning to package this somewhere else then pip.

If you want to work on providing a package / snap feel free to to so. I guess for snap it would make sense to ping BigMichi1 for advice.  
I guess for the different repos one would need to talk to the maintainers.

Sorry for not being more helpful, but feel free to ask more questions.
