### ISSUE TITLE
Snap package incompatible with Certbot 3.0

### ISSUE THREAD

**Issue by DaHoC** [ctrlaltcoop/certbot-dns-hetzner#32]
On Ubuntu 24.04.1 LTS, the following command fails (since more or less than a month?):

```
sudo certbot certonly --authenticator dns-hetzner --dns-hetzner-credentials /path/to/hcloud_dns_token.ini --staple-ocsp --email <redacted>
```
with following error message:

```
The following plugins are using an outdated python version and must be updated to be compatible with Certbot 3.0. Please see https://community.letsencrypt.org/t/certbot-3-0-could-have-potential-third-party-snap-breakages/226940 for more information:
  * certbot-dns-hetzner
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --dns-hetzner-credentials /path/to/hcloud_dns_token.ini
```

`sudo certbot plugins` does not list the `certbot-dns-hetzner` plugin and displays the same message:

```
The following plugins are using an outdated python version and must be updated to be compatible with Certbot 3.0. Please see https://community.letsencrypt.org/t/certbot-3-0-could-have-potential-third-party-snap-breakages/226940 for more information:
  * certbot-dns-hetzner
```

### Steps to reproduce:
On Ubuntu 24.04.1 LTS, install snapd and issue following commands:

```
sudo snap install --classic certbot
sudo snap set certbot trust-plugin-with-root=ok
sudo snap install certbot-dns-hetzner
sudo snap connect certbot:plugin certbot-dns-hetzner
sudo snap connect certbot-dns-hetzner:certbot-metadata certbot:certbot-metadata
```
and afterwards, try the above command `sudo certbot certonly --authenticator dns-hetzner ...`

As an alternative working solution, I switched to using pip instead of snap as package manager for certbot, as recommended.

**Comment by kthy** [comment]
As far as I know, the `snap install certbot-dns-hetzner` actually installs the very outdated version of the plugin that this was forked from, https://github.com/BigMichi1/certbot-dns-hetzner/

See https://snapcraft.io/certbot-dns-hetzner for verification.

**Comment by DaHoC** [comment]
Thank you for mentioning this in the README - there is a small typo however: `Not working with nap` (instead of snap)
