### ISSUE TITLE
Pinned parsedatetime dependency causes error on macOS using HomeBrew / CertBot 1.9.0

### ISSUE THREAD

**Issue by robertoschwald** [ctrlaltcoop/certbot-dns-hetzner#9]
When installing the plugin in HomeBrew provided certbot, a dependency error is thrown, as parsedatetime is pinned to <=2.5

```
brew install certbot
pip3 install --prefix=$(brew --prefix certbot)/libexec/vendor certbot-dns-hetzner
```

```
certbot certonly \
--authenticator dns-hetzner \
--dns-hetzner-credentials /usr/local/etc/certbot-hetzner.ini \
--dns-hetzner-propagation-seconds 120 \
--email hostmaster@example.com --agree-tos -d myhost.example.com
```

Error:
An unexpected error occurred:
pkg_resources.VersionConflict: (parsedatetime 2.6 (/usr/local/Cellar/certbot/1.9.0/libexec/vendor/lib/python3.9/site-packages), Requirement.parse('parsedatetime<=2.5'))

Is there a reason why parsedatetime is pinned?

**Comment by l0rn** [comment]
unfortunately yes, because of python2 compatibility.... Personally i would drop python2 support, but as long as certbot itself supports python2 i think the plugins should remain compatible as well:

https://github.com/bear/parsedatetime/issues/246
